// src/types/database.types.ts

export type WishlistItem = Database['public']['Tables']['wishlist_item']['Row'];
export type WishlistItemInsert = Database['public']['Tables']['wishlist_item']['Insert'];
export type WishlistItemUpdate = Database['public']['Tables']['wishlist_item']['Update'];

export type ShoppingList = Database['public']['Tables']['shopping_list']['Row'];
export type ShoppingListInsert = Database['public']['Tables']['shopping_list']['Insert'];
export type ShoppingListUpdate = Database['public']['Tables']['shopping_list']['Update'];

export type ShoppingListItem = Database['public']['Tables']['shopping_list_item']['Row'];
export type ShoppingListItemInsert = Database['public']['Tables']['shopping_list_item']['Insert'];
export type ShoppingListItemUpdate = Database['public']['Tables']['shopping_list_item']['Update'];

// Wishlist Item - The actual type from your database
export interface WishlistItem {
    id: string;
    owner_id: string;
    title: string;
    category: string | null;
    status: 'wanted' | 'considering' | 'on_hold' | 'purchased' | 'declined';
    url: string | null;
    notes: string | null;
    priority: number | null; // 1-5
    price_cents: number | null;
    currency: string | null;
    image_url: string | null;
    purchased_at: string | null;
    vendor: string | null;
    brand: string | null;
    color: string | null;
    size: string | null;
    created_at: string;
}

// Shopping List - The actual type from your database
export interface ShoppingList {
    id: string;
    owner_id: string;
    name: string;
    notes: string | null;
    created_at: string;
}

// Shopping List Item - The actual type from your database
export interface ShoppingListItem {
    id: string;
    owner_id: string;
    list_id: string;
    item_name: string;
    quantity: number | null;
    unit: string | null;
    needed_by: string | null;
    priority: number | null; // 1-5
    notes: string | null;
    is_done: boolean;
    created_at: string;
    category: string | null;
    store_preference: string | null;
    aisle: string | null;
    last_purchased_at: string | null;
}

// Placeholder Database type (this would normally be auto-generated by Supabase CLI)
export interface Database {
    public: {
        Tables: {
            wishlist_item: {
                Row: WishlistItem;
                Insert: Omit<WishlistItem, 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: Partial<Omit<WishlistItem, 'id' | 'created_at'>>;
            };
            shopping_list: {
                Row: ShoppingList;
                Insert: Omit<ShoppingList, 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: Partial<Omit<ShoppingList, 'id' | 'created_at'>>;
            };
            shopping_list_item: {
                Row: ShoppingListItem;
                Insert: Omit<ShoppingListItem, 'id' | 'created_at'> & {
                    id?: string;
                    created_at?: string;
                };
                Update: Partial<Omit<ShoppingListItem, 'id' | 'created_at'>>;
            };
        };
    };
}