name: Discord Deployment Notifications

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  deployment_status:

jobs:
  notify-start:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get changed files
        id: changes
        run: |
          echo "files=$(git diff --name-only HEAD^ HEAD | head -5 | tr '\n' ', ' | sed 's/,$//')" >> $GITHUB_OUTPUT
          echo "file_count=$(git diff --name-only HEAD^ HEAD | wc -l)" >> $GITHUB_OUTPUT

      - name: Get commit stats
        id: stats
        run: |
          echo "additions=$(git diff --shortstat HEAD^ HEAD | grep -o '[0-9]* insertion' | cut -d' ' -f1 || echo '0')" >> $GITHUB_OUTPUT
          echo "deletions=$(git diff --shortstat HEAD^ HEAD | grep -o '[0-9]* deletion' | cut -d' ' -f1 || echo '0')" >> $GITHUB_OUTPUT

      - name: Notify Deployment Started
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "🚀 Deployment Started"
          description: |
            **Project:** rosendohq
            **Branch:** `${{ github.ref_name }}`
            **Author:** ${{ github.actor }}
            **Commit:** [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Message:** ${{ github.event.head_commit.message }}

            **📊 Changes:**
            • **Files changed:** ${{ steps.changes.outputs.file_count }}
            • **Lines added:** +${{ steps.stats.outputs.additions }}
            • **Lines removed:** -${{ steps.stats.outputs.deletions }}

            **📁 Modified files:** ${{ steps.changes.outputs.files }}
          color: 0xffa500
          username: "GitHub Deploy Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

  notify-pr:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get PR stats
        id: pr_stats
        run: |
          echo "commits=$(echo '${{ github.event.pull_request.commits }}')" >> $GITHUB_OUTPUT
          echo "additions=$(echo '${{ github.event.pull_request.additions }}')" >> $GITHUB_OUTPUT
          echo "deletions=$(echo '${{ github.event.pull_request.deletions }}')" >> $GITHUB_OUTPUT
          echo "changed_files=$(echo '${{ github.event.pull_request.changed_files }}')" >> $GITHUB_OUTPUT

      - name: Notify Pull Request
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "📝 New Pull Request"
          description: |
            **PR:** [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }})
            **Author:** ${{ github.actor }}
            **Branch:** `${{ github.head_ref }}` → `${{ github.base_ref }}`

            **📊 PR Stats:**
            • **Commits:** ${{ steps.pr_stats.outputs.commits }}
            • **Files changed:** ${{ steps.pr_stats.outputs.changed_files }}
            • **Lines:** +${{ steps.pr_stats.outputs.additions }} / -${{ steps.pr_stats.outputs.deletions }}
          color: 0x00aaff
          username: "GitHub PR Bot"
          avatar_url: "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

  # This job listens to Vercel deployment status changes
  vercel-deployment-status:
    runs-on: ubuntu-latest
    if: github.event_name == 'deployment_status'
    steps:
      - name: Get deployment time
        id: timing
        run: |
          echo "deployed_at=$(date -u +'%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_OUTPUT

      - name: Notify Deployment Success
        if: github.event.deployment_status.state == 'success'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "✅ Deployment Successful"
          description: |
            **Project:** rosendohq
            **Environment:** 🌍 ${{ github.event.deployment.environment }}
            **Live URL:** [${{ github.event.deployment.payload.web_url || 'rosendohq.vercel.app' }}](${{ github.event.deployment.payload.web_url || 'https://rosendohq.vercel.app' }})
            **Deployed at:** ${{ steps.timing.outputs.deployed_at }}

            **🔗 Quick Links:**
            • [View Site](${{ github.event.deployment.payload.web_url || 'https://rosendohq.vercel.app' }})
            • [Vercel Dashboard](https://vercel.com/dashboard)
            • [Commit Details](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            **📱 Test your deployment:**
            • Desktop: [${{ github.event.deployment.payload.web_url || 'rosendohq.vercel.app' }}](${{ github.event.deployment.payload.web_url || 'https://rosendohq.vercel.app' }})
            • Mobile view: Check responsive design
          color: 0x00ff00
          username: "Vercel Deploy Bot"
          avatar_url: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico"

      - name: Notify Deployment Failure
        if: github.event.deployment_status.state == 'failure'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "❌ Deployment Failed"
          description: |
            **Project:** rosendohq
            **Environment:** 🔴 ${{ github.event.deployment.environment }}
            **Author:** ${{ github.actor }}
            **Commit:** [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            **🔍 Debug Links:**
            • [GitHub Actions Log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            • [Vercel Dashboard](https://vercel.com/dashboard)
            • [Deployment Details](${{ github.event.deployment_status.target_url }})

            **⚠️ Action Required:** Check the Vercel deployment logs to diagnose the issue.

            **Error Details:**
            • **Status:** ${{ github.event.deployment_status.state }}
            • **Description:** ${{ github.event.deployment_status.description }}
          color: 0xff0000
          username: "Vercel Deploy Bot"
          avatar_url: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico"

      - name: Notify Deployment Error
        if: github.event.deployment_status.state == 'error'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          title: "🚨 Deployment Error"
          description: |
            **Project:** rosendohq
            **Environment:** ⚠️ ${{ github.event.deployment.environment }}
            **Author:** ${{ github.actor }}
            **Commit:** [`${{ github.sha }}`](https://github.com/${{ github.repository }}/commit/${{ github.sha }})

            **🔍 Debug Links:**
            • [GitHub Actions Log](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})
            • [Vercel Dashboard](https://vercel.com/dashboard)
            • [Deployment Details](${{ github.event.deployment_status.target_url }})

            **💥 Critical Error:** The deployment encountered a system error.

            **Error Details:**
            • **Status:** ${{ github.event.deployment_status.state }}
            • **Description:** ${{ github.event.deployment_status.description }}
          color: 0x800000
          username: "Vercel Deploy Bot"
          avatar_url: "https://assets.vercel.com/image/upload/front/favicon/vercel/favicon.ico"
